---
- hosts: localhost
  tasks:
    - name: create file
      file:
        path: /home/thomas/new
        state: touch
        
    - name: add line
      lineinfile:
        path: /home/thomas/new
        line: "{{ ansible_default_ipv4.address }}"
      
