---
- hosts: localhost
  tasks:
    - name: create file
      file:
        path: /tmp/newfile
        state: touch
        
    - name: add line
      lineinfile:
        path: /tmp/newfile
        line: "{{ ansible_default_ipv4.address }}"
      
